# Generated by Django 5.1.2 on 2024-11-06 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', error_messages={'blank': 'Description cannot be blank', 'null': 'Description cannot be null', 'unique': 'Description is already in use'}, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', error_messages={'blank': 'Name cannot be blank', 'null': 'Name cannot be null'}, max_length=255)),
                ('address', models.CharField(default='', error_messages={'blank': 'Address cannot be blank', 'null': 'Address cannot be null'}, max_length=255)),
                ('phone_number', models.CharField(default='', error_messages={'blank': 'Phone number cannot be blank', 'max_length': 'Phone number cannot be longer than 15 characters', 'null': 'Phone number cannot be null', 'unique': 'Phone number is already in use'}, max_length=15, unique=True)),
                ('email', models.EmailField(default='', error_messages={'blank': 'Email cannot be blank', 'invalid': 'Email must be valid', 'null': 'Email cannot be null', 'unique': 'Email is already in use'}, max_length=254, unique=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='institutions.institutiontype')),
            ],
        ),
    ]
