# Generated by Django 5.1.2 on 2024-11-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='type',
            new_name='institution_type',
        ),
    ]
