# Generated by Django 5.1.2 on 2024-12-08 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0002_rename_type_institution_institution_type'),
        ('patients', '0001_initial'),
        ('practitioners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(error_messages={'blank': 'Exam type cannot be blank', 'null': 'Exam type cannot be null'}, max_length=50)),
                ('exam_date', models.DateField(error_messages={'blank': 'Exam date cannot be blank', 'invalid': 'Invalid date format', 'null': 'Exam date cannot be null'})),
                ('result', models.TextField(blank=True, default='', null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='institutions.institution')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='patients.patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='practitioners.practitioner')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(error_messages={'blank': 'Medication cannot be blank', 'null': 'Medication cannot be null'}, max_length=100)),
                ('dosage', models.CharField(error_messages={'blank': 'Dosage cannot be blank', 'null': 'Dosage cannot be null'}, max_length=50)),
                ('frequency', models.CharField(error_messages={'blank': 'Frequency cannot be blank', 'null': 'Frequency cannot be null'}, max_length=50)),
                ('prescription_date', models.DateField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_prescriptions', to='institutions.institution')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_prescriptions', to='patients.patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_prescriptions', to='practitioners.practitioner')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(error_messages={'blank': 'Creation date cannot be blank', 'invalid': 'Invalid date format', 'null': 'Creation date cannot be null'})),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='institutions.institution')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='practitioners.practitioner')),
            ],
        ),
    ]
