# Generated by Django 5.1.2 on 2024-12-08 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_accesshistory'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'Name cannot be blank', 'null': 'Name cannot be null', 'unique': 'A disease with this name already exists.'}, max_length=100, unique=True)),
                ('description', models.CharField(error_messages={'blank': 'Description cannot be blank', 'null': 'Description cannot be null'}, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(blank=True, default='', max_length=255)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disease_history', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_diagnosis', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='medical_records.disease')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='medical_records.diseasehistory')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('history', 'disease'), name='unique_history_disease')],
            },
        ),
    ]
