# Generated by Django 5.1.2 on 2024-11-25 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0002_rename_type_institution_institution_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PractitionerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', error_messages={'blank': 'Description cannot be blank', 'null': 'Description cannot be null', 'unique': 'Description is already in use'}, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', error_messages={'blank': 'Name cannot be blank', 'null': 'Name cannot be null'}, max_length=255)),
                ('cpf', models.CharField(default='', error_messages={'blank': 'CPF cannot be blank', 'max_length': 'CPF cannot be longer than 11 characters', 'null': 'CPF cannot be null', 'unique': 'CPF is already in use'}, max_length=11, unique=True)),
                ('registration', models.CharField(error_messages={'blank': 'Registration cannot be blank', 'max_length': 'Registration cannot be longer than 50 characters', 'null': 'Registration cannot be null', 'unique': 'Registration is already in use'}, max_length=50, unique=True)),
                ('practitioner_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioners', to='institutions.institution')),
                ('practitioner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioners', to='practitioners.practitionertype')),
            ],
        ),
    ]
