# Generated by Django 5.1.2 on 2024-12-07 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0002_rename_type_institution_institution_type'),
        ('patients', '0001_initial'),
        ('practitioners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', error_messages={'blank': 'Description cannot be blank', 'null': 'Description cannot be null', 'unique': 'Description is already in use'}, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateField(error_messages={'blank': 'Consultation date cannot be blank', 'invalid': 'Invalid date format', 'null': 'Consultation date cannot be null'})),
                ('consultation_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='institutions.institution')),
                ('consultation_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
                ('consultation_practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='practitioners.practitioner')),
                ('consultation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='consultations.consultationtype')),
            ],
        ),
    ]
