# Generated by Django 5.1.2 on 2024-11-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', error_messages={'blank': 'Name cannot be blank', 'null': 'Name cannot be null'}, max_length=255)),
                ('date_birth', models.DateField(error_messages={'blank': 'Date of birth cannot be blank', 'invalid': 'Invalid date format', 'null': 'Date of birth cannot be null'})),
                ('sex', models.CharField(choices=[('M', 'Masculine'), ('F', 'Feminine')], default='M', error_messages={'blank': 'Sex cannot be blank', 'max_length': 'Sex cannot be longer than 1 character', 'null': 'Sex cannot be null'}, max_length=1)),
                ('cpf', models.CharField(default='', error_messages={'blank': 'CPF cannot be blank', 'max_length': 'CPF cannot be longer than 11 characters', 'null': 'CPF cannot be null', 'unique': 'CPF is already in use'}, max_length=11, unique=True)),
                ('address', models.CharField(default='', error_messages={'blank': 'Address cannot be blank', 'null': 'Address cannot be null'}, max_length=255)),
                ('phone_number', models.CharField(default='', error_messages={'blank': 'Phone number cannot be blank', 'max_length': 'Phone number cannot be longer than 15 characters', 'null': 'Phone number cannot be null', 'unique': 'Phone number is already in use'}, max_length=15, unique=True)),
                ('email', models.EmailField(default='', error_messages={'blank': 'Email cannot be blank', 'invalid': 'Email must be valid', 'null': 'Email cannot be null', 'unique': 'Email is already in use'}, max_length=254, unique=True)),
            ],
        ),
    ]
